export default function handler(req, res) {
    res.status(200).json({
        "technologies":{
			"maintitle":"Technologies",
			"title":"No matter your tech needs, we have the skills to address them.",
			"subtitle":"Get seamless integration with below technology stack and become the global leader in digital innovation.",
			"technologieslist":[
				{
					"technologiesmenu":"CMS",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/wordpress.svg",
								"alt":"wordpress"
							},
							"title":"WordPress"
						},
						{
							"image":{
								"url":"/images/joomla.svg",
								"alt":"joomla"
							},
							"title":"Joomla"
						},
						{
							"image":{
								"url":"/images/hubspot.svg",
								"alt":"hubspot"
							},
							"title":"HubSpot"
						}
					]
				},
				{
					"technologiesmenu":"Ecommerce",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/woocommerce.svg",
								"alt":"woocommerce"
							},
							"title":"WooCommerce"
						},
						{
							"image":{
								"url":"/images/shopify.svg",
								"alt":"shopify"
							},
							"title":"Shopify"
						},
						{
							"image":{
								"url":"/images/magento.svg",
								"alt":"magento"
							},
							"title":"Magento"
						}
					]
				},
				{
					"technologiesmenu":"Front-end",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/html.svg",
								"alt":"html"
							},
							"title":"HTML"
						},
						{
							"image":{
								"url":"/images/css.svg",
								"alt":"css"
							},
							"title":"CSS"
						},
						{
							"image":{
								"url":"/images/jquery.svg",
								"alt":"jquery"
							},
							"title":"jQuery"
						},
						{
							"image":{
								"url":"/images/react.svg",
								"alt":"react"
							},
							"title":"Reactjs"
						},
						{
							"image":{
								"url":"/images/nextjs.svg",
								"alt":"nextjs"
							},
							"title":"Nextjs"
						},
						{
							"image":{
								"url":"/images/javascript.svg",
								"alt":"javascript"
							},
							"title":"JavaScript"
						}
					]
				},
				{
					"technologiesmenu":"Backend",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/php.svg",
								"alt":"php"
							},
							"title":"PHP"
						},
						{
							"image":{
								"url":"/images/laravel.svg",
								"alt":"laravel"
							},
							"title":"Laravel"
						},
						{
							"image":{
								"url":"/images/codeigniter.svg",
								"alt":"codeigniter"
							},
							"title":"CodeIgniter"
						},
						{
							"image":{
								"url":"/images/graphql.svg",
								"alt":"graphql"
							},
							"title":"GraphQL"
						}
					]
				},
				{
					"technologiesmenu":"Mobile App",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/android.svg",
								"alt":"android"
							},
							"title":"Android"
						},
						{
							"image":{
								"url":"/images/ios.svg",
								"alt":"ios"
							},
							"title":"iOS"
						},
						{
							"image":{
								"url":"/images/react-native.svg",
								"alt":"react-native"
							},
							"title":"React Native"
						},
						{
							"image":{
								"url":"/images/flutter.svg",
								"alt":"flutter"
							},
							"title":"Flutter"
						}
					]
				},
				{
					"technologiesmenu":"Databases",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/sql.svg",
								"alt":"sql"
							},
							"title":"SQL"
						},
						{
							"image":{
								"url":"/images/firebase.svg",
								"alt":"firebase"
							},
							"title":"Firebase"
						},
						{
							"image":{
								"url":"/images/mongodb.svg",
								"alt":"mongodb"
							},
							"title":"MongoDB"
						},
						{
							"image":{
								"url":"/images/postgresql.svg",
								"alt":"postgresql"
							},
							"title":"PostgreSQL"
						}
					]
				},
				{
					"technologiesmenu":"Tools",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/vscode.svg",
								"alt":"vscode"
							},
							"title":"VS Code"
						},
						{
							"image":{
								"url":"/images/sublime.svg",
								"alt":"sublime"
							},
							"title":"Sublime"
						},
						{
							"image":{
								"url":"/images/github.svg",
								"alt":"github"
							},
							"title":"GitHub"
						},
						{
							"image":{
								"url":"/images/bitbucket.svg",
								"alt":"bitbucket"
							},
							"title":"Bitbucket"
						},
						{
							"image":{
								"url":"/images/figma.svg",
								"alt":"figma"
							},
							"title":"Figma"
						},
						{
							"image":{
								"url":"/images/sketch.svg",
								"alt":"sketch"
							},
							"title":"Sketch"
						},
						{
							"image":{
								"url":"/images/photoshop.svg",
								"alt":"Photoshop"
							},
							"title":"Figma"
						},
						{
							"image":{
								"url":"/images/illustrator.svg",
								"alt":"illustrator"
							},
							"title":"Illustrator"
						},
						{
							"image":{
								"url":"/images/adobe-xd.svg",
								"alt":"adobe-xd"
							},
							"title":"Adobe XD"
						},
						{
							"image":{
								"url":"/images/invision.svg",
								"alt":"invision"
							},
							"title":"InVision"
						}
					]
				},
				{
					"technologiesmenu":"PMS",
					"technologiesinfo":[
						{
							"image":{
								"url":"/images/jira.svg",
								"alt":"jira"
							},
							"title":"Jira"
						},
						{
							"image":{
								"url":"/images/asana.svg",
								"alt":"asana"
							},
							"title":"Asana"
						},
						{
							"image":{
								"url":"/images/slack.svg",
								"alt":"slack"
							},
							"title":"Slack"
						},
						{
							"image":{
								"url":"/images/trello.svg",
								"alt":"trello"
							},
							"title":"Trello"
						},
						{
							"image":{
								"url":"/images/monday.svg",
								"alt":"monday"
							},
							"title":"Monday"
						}
					]
				}
			]
		}
    });
}